services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    volumes:
      - .:/app
      - "/app/node_modules"
    environment:
      - SERVER_PORT=3030
